export const city = state => state.city
export const centerPosition = state => state.centerPosition
export const searchHistory = state => state.history
export const home = state => state.home
export const company = state => state.company
export const startPois = state => state.startPois
export const endPois = state => state.endPois
export const price = state => state.price
export const poinWayList = state => state.poinWayList
export const AddPoinWay = state => state.addPoinWay
export const callCar = state => state.callCar
export const resvernation = state => state.resvernation
export const showLayer = state => state.showLayer